name: node-release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v1
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: npm ci
        run: npm ci

      - name: npm test
        run: npm test
        env:
          CI: true

      - name: npm shrinkwrap
        run: npm shrinkwrap

      - run: npm run build

      - name: npm auth & publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
